CREATE TRIGGER [DELETE_User]
   ON dbo.[AspNetUsers]
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM dbo.[Baskets] WHERE UserID IN (SELECT Id FROM DELETED)
 DELETE FROM dbo.[Stores] WHERE OwnerID IN (SELECT Id FROM DELETED)
 DELETE FROM dbo.[AspNetUsers] WHERE Id IN (SELECT Id FROM DELETED)
END
GO
CREATE TRIGGER [DELETE_Basket]
   ON dbo.[Baskets]
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM dbo.[BasketItems] WHERE BasketID IN (SELECT Id FROM DELETED)
 DELETE FROM dbo.[Baskets] WHERE Id IN (SELECT Id FROM DELETED)
END
GO
CREATE TRIGGER [DELETE_Shipping]
   ON dbo.[Shippings]
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 UPDATE dbo.[Orders] SET ShippingID = NULL WHERE ShippingID IN (SELECT Id FROM DELETED)
 DELETE FROM dbo.[Shippings] WHERE Id IN (SELECT Id FROM DELETED)
END
GO
CREATE TRIGGER [DELETE_Order]
   ON dbo.[Orders]
   INSTEAD OF DELETE
AS 
BEGIN
 SET NOCOUNT ON;
 DELETE FROM dbo.[Trackings] WHERE OrderID IN (SELECT Id FROM DELETED)
 DELETE FROM dbo.[Orders] WHERE Id IN (SELECT Id FROM DELETED)
END